author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 2
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/v3/encrypt'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第三个用户配置
  # 以下配置为签到
  # 这里默认仅适配武汉船舶职业技术学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '2001230188'
      #password 密码
      password: 'wang1181996824'
      #address 地址，定位信息
      address: '山东省潍坊市寒亭区河滨南街'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: '5196715a63e24c72830b6e5c8137bb32'
      #school 学校全称
      schoolName: 潍坊职业学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 119.211565
      #lat 纬度
      lat: 37.09263
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      # 代理ip信息（若无可忽略本设置、该配置仅供您所在环境ip被ban且自己拥有代理ip使用）（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy: ''
      # isOffset 坐标偏移开关，默认打开坐标偏移开关，若一直出现不在签到范围且确保自己填写的lon和lat在坐标范围内，请尝试关闭本功能
      isOffset: true
      # 表单信息
      forms:
        - form:
            title: 体温情况
            value: 小于37.3℃
        - form:
            title: 是否有发热，干咳、乏力、咽痛、嗅（味）觉减退、腹泻等症状？
            value: 否
